language: node_js
node_js:
  - "6.9"
branches:
  only:
    - master
before_script:
  - git config --global user.name "Donna via CI"
  - git config --global user.email "donnamatata@gmail.com"
  - sed -i "s/donnamatata/${__GITHUB_TOKEN__}/" _config.yml
